#Requires AutoHotkey v2.0
#SingleInstance Force
; ============================================================================
;  ClaudeSnap  —  snip / paste straight into the Claude desktop app.
;
;  Press one key to grab a screen region and drop it into Claude's message box.
;  Press another to post it. You never have to leave what you're working on.
;
;  You do NOT edit this file to change keys — edit config.ini next to it,
;  then right-click the tray icon and choose "Reload".
; ============================================================================

cfg := A_ScriptDir "\config.ini"
SetTitleMatchMode(2)              ; match the Claude window by a partial title

; --- settings (read from config.ini, with safe fallbacks) -------------------
global WinMatch     := IniRead(cfg, "Claude",   "WinMatch",       "Claude ahk_exe Claude.exe")
global LaunchID     := IniRead(cfg, "Claude",   "LaunchID",       "Claude_pzs8sxrjxfjjc!Claude")
global RestoreFocus := IniRead(cfg, "Behavior", "RestoreFocus",   "1")
global AutoPost     := IniRead(cfg, "Behavior", "AutoPostOnSnip", "0")
global Debug        := IniRead(cfg, "Behavior", "Debug",          "0")

keySnip := IniRead(cfg, "Hotkeys", "SnipAndSend",    "!1")
keySel  := IniRead(cfg, "Hotkeys", "CopySelection",  "!2")
keyAll  := IniRead(cfg, "Hotkeys", "CopyAllOnPage",  "!3")
keyPost := IniRead(cfg, "Hotkeys", "Post",           "!0")

; --- bind the hotkeys -------------------------------------------------------
Hotkey(keySnip, SnipAndSend)
Hotkey(keySel,  CopySelectionToClaude)
Hotkey(keyAll,  CopyAllToClaude)
Hotkey(keyPost, PostToClaude)

; --- tray menu (friendly for non-coders) ------------------------------------
A_TrayMenu.Delete()
A_TrayMenu.Add("Settings…", (*) => ShowSettings())
A_TrayMenu.Default := "Settings…"          ; double-click the tray icon opens it
A_TrayMenu.Add()
A_TrayMenu.Add("Edit config.ini directly", (*) => Run(cfg))
A_TrayMenu.Add("Reload", (*) => Reload())
A_TrayMenu.Add()
A_TrayMenu.Add("Exit", (*) => ExitApp())

TrayTip("ClaudeSnap is running",
        "Snip: " keySnip "   Copy: " keySel "   All: " keyAll "   Send: " keyPost, 1)

; ============================================================================
;  actions
; ============================================================================

; Alt+1 — grab a region of the screen and drop it into Claude's message box.
SnipAndSend(*) {
    global RestoreFocus, AutoPost
    Log("Snip fired")
    prev := WinActive("A")
    KeyWait("Alt", "T1")              ; let go of Alt so the snip key isn't mangled
    A_Clipboard := ""                 ; clear so we can detect the new snip
    Send("#+s")                       ; Windows built-in "snip region to clipboard"
    if !ClipWait(60, 1)               ; wait up to 60s for the snip (1 = images too)
        return
    PasteIntoClaude(prev, 200)
    if (AutoPost = "1")
        Post(prev)
}

; Alt+2 — copy whatever text is highlighted right now, then send it to Claude.
CopySelectionToClaude(*) {
    Log("CopySelection fired")
    GrabTextToClaude("^c")
}

; Alt+3 — select everything on the page, copy it, then send it to Claude.
CopyAllToClaude(*) {
    Log("CopyAll fired")
    GrabTextToClaude("^a^c")
}

; Copy from the user's current window (using copyKeys), then paste into Claude.
GrabTextToClaude(copyKeys) {
    prev := WinActive("A")
    KeyWait("Alt", "T1")              ; release Alt or ^c becomes ^!c and fails
    A_Clipboard := ""                 ; clear so we know when the copy lands
    Send(copyKeys)                    ; copy happens in the window you're in
    if !ClipWait(2) {                 ; wait up to 2s for text
        TrayTip("Nothing copied", "No text was selected to send.", 2)
        return
    }
    PasteIntoClaude(prev, 120)
}

; Alt+0 — send / post the current message.
PostToClaude(*) {
    Log("Post fired")
    Post(WinActive("A"))
}

; --- shared helpers ---------------------------------------------------------

; Focus Claude, paste the clipboard, then hand focus back.
PasteIntoClaude(prev, settle) {
    global RestoreFocus
    if !FocusClaude()
        return
    Send("^v")
    Sleep(settle)                     ; let it attach before we leave
    if (RestoreFocus = "1" && prev)
        WinActivate("ahk_id " prev)
}

; Focus Claude, press Enter, then hand focus back.
Post(prev) {
    global RestoreFocus
    KeyWait("Alt", "T1")
    if !FocusClaude()
        return
    Send("{Enter}")
    Sleep(80)
    if (RestoreFocus = "1" && prev)
        WinActivate("ahk_id " prev)
}

; Bring the Claude desktop window to the front — whatever state it's in.
; Handles: focused, minimised, hidden to the tray, or not running at all.
FocusClaude() {
    global WinMatch, LaunchID
    DetectHiddenWindows(true)                  ; so tray-hidden windows count
    id := WinExist(WinMatch)
    if !id {                                   ; not running — launch it
        if (LaunchID != "")
            Run("explorer.exe shell:AppsFolder\" LaunchID)
        if !WinWait(WinMatch, , 8) {
            TrayTip("Couldn't open Claude",
                    "Check LaunchID / WinMatch in config.ini.", 3)
            return 0
        }
        id := WinExist(WinMatch)
    }
    if (WinGetMinMax("ahk_id " id) = -1)       ; -1 = minimised
        WinRestore("ahk_id " id)
    WinShow("ahk_id " id)                       ; un-hide if it was in the tray
    WinActivate("ahk_id " id)
    ok := WinWaitActive("ahk_id " id, , 3)
    Log("FocusClaude id=" id " activated=" (ok ? "yes" : "no"))
    return ok
}

; Write a line to claudesnap.log when Debug=1 in config.ini.
Log(msg) {
    global Debug
    if (Debug = "1")
        try FileAppend(FormatTime(, "HH:mm:ss") "  " msg "`n", A_ScriptDir "\claudesnap.log")
}

; A tiny settings window — click a box, press the keys you want, Save.
ShowSettings(*) {
    global cfg
    g := Gui("+AlwaysOnTop -MinimizeBox", "ClaudeSnap settings")
    g.SetFont("s10", "Segoe UI")
    g.Add("Text", "xm", "Click a box, then press the keys you'd like to use:")

    g.Add("Text",   "xm y+14 w180",       "Snip screenshot → Claude")
    hkSnip := g.Add("Hotkey", "x+6 yp-4 w150", IniRead(cfg, "Hotkeys", "SnipAndSend",   "!1"))
    g.Add("Text",   "xm y+10 w180",       "Copy highlighted → Claude")
    hkSel  := g.Add("Hotkey", "x+6 yp-4 w150", IniRead(cfg, "Hotkeys", "CopySelection", "!2"))
    g.Add("Text",   "xm y+10 w180",       "Select-all page → Claude")
    hkAll  := g.Add("Hotkey", "x+6 yp-4 w150", IniRead(cfg, "Hotkeys", "CopyAllOnPage", "!3"))
    g.Add("Text",   "xm y+10 w180",       "Send / post message")
    hkPost := g.Add("Hotkey", "x+6 yp-4 w150", IniRead(cfg, "Hotkeys", "Post",          "!0"))

    cbRestore := g.Add("Checkbox", "xm y+16", "Return to my window after each action")
    cbRestore.Value := (IniRead(cfg, "Behavior", "RestoreFocus",   "1") = "1")
    cbAuto := g.Add("Checkbox", "xm y+8", "Send screenshot the moment I finish snipping")
    cbAuto.Value := (IniRead(cfg, "Behavior", "AutoPostOnSnip", "0") = "1")

    g.Add("Button", "xm y+18 w120 Default", "Save && Reload").OnEvent("Click", Save)
    g.Add("Button", "x+10 w90", "Cancel").OnEvent("Click", (*) => g.Destroy())
    g.OnEvent("Escape", (*) => g.Destroy())
    g.Show()

    Save(*) {
        for hk in [hkSnip, hkSel, hkAll, hkPost] {
            if (hk.Value = "") {
                MsgBox("Every box needs a key combo.", "ClaudeSnap", "Iconx 4096")
                return
            }
        }
        IniWrite(hkSnip.Value, cfg, "Hotkeys", "SnipAndSend")
        IniWrite(hkSel.Value,  cfg, "Hotkeys", "CopySelection")
        IniWrite(hkAll.Value,  cfg, "Hotkeys", "CopyAllOnPage")
        IniWrite(hkPost.Value, cfg, "Hotkeys", "Post")
        IniWrite(cbRestore.Value ? "1" : "0", cfg, "Behavior", "RestoreFocus")
        IniWrite(cbAuto.Value    ? "1" : "0", cfg, "Behavior", "AutoPostOnSnip")
        g.Destroy()
        Reload()                                ; restart with the new keys
    }
}
