#Requires AutoHotkey v2.0
#SingleInstance Force
; ============================================================================
;  ClaudeSnap  —  snip / paste straight into the Claude desktop app.
;
;  Press one key to grab a screen region and drop it into Claude's message box.
;  Press another to post it. You never have to leave what you're working on.
;
;  You do NOT edit this file to change keys — edit config.ini next to it,
;  then right-click the tray icon and choose "Reload".
; ============================================================================

cfg := A_ScriptDir "\config.ini"

; --- settings (read from config.ini, with safe fallbacks) -------------------
global WinMatch     := IniRead(cfg, "Claude",   "WinMatch",       "ahk_exe Claude.exe")
global RestoreFocus := IniRead(cfg, "Behavior", "RestoreFocus",   "1")
global AutoPost     := IniRead(cfg, "Behavior", "AutoPostOnSnip", "0")

keySnip  := IniRead(cfg, "Hotkeys", "SnipAndSend",   "^!s")
keyPaste := IniRead(cfg, "Hotkeys", "SendClipboard", "^!d")
keyPost  := IniRead(cfg, "Hotkeys", "Post",          "^!f")

; --- bind the hotkeys -------------------------------------------------------
Hotkey(keySnip,  SnipAndSend)
Hotkey(keyPaste, SendClipboardText)
Hotkey(keyPost,  PostToClaude)

; --- tray menu (friendly for non-coders) ------------------------------------
A_TrayMenu.Delete()
A_TrayMenu.Add("ClaudeSnap", (*) => 0)
A_TrayMenu.Disable("ClaudeSnap")
A_TrayMenu.Add()
A_TrayMenu.Add("Edit hotkeys (config.ini)", (*) => Run(cfg))
A_TrayMenu.Add("Reload after editing",      (*) => Reload())
A_TrayMenu.Add()
A_TrayMenu.Add("Exit", (*) => ExitApp())

TrayTip("ClaudeSnap is running",
        "Snip: " keySnip "    Paste: " keyPaste "    Post: " keyPost, 1)

; ============================================================================
;  actions
; ============================================================================

; Grab a region of the screen and drop it into Claude's message box.
SnipAndSend(*) {
    global WinMatch, RestoreFocus, AutoPost
    prev := WinActive("A")
    A_Clipboard := ""                 ; clear so we can detect the new snip
    Send("#+s")                       ; Windows built-in "snip region to clipboard"
    if !ClipWait(60, 1)               ; wait up to 60s for the snip (1 = images too)
        return
    if !FocusClaude()
        return
    Send("^v")
    Sleep(200)                        ; let the image attach
    if (AutoPost = "1")
        Send("{Enter}")
    if (RestoreFocus = "1" && prev)
        WinActivate("ahk_id " prev)
}

; Paste whatever is already on the clipboard (text or image) into Claude.
SendClipboardText(*) {
    global RestoreFocus
    prev := WinActive("A")
    if !FocusClaude()
        return
    Send("^v")
    Sleep(120)
    if (RestoreFocus = "1" && prev)
        WinActivate("ahk_id " prev)
}

; Send / post the current message (Enter inside Claude).
PostToClaude(*) {
    global RestoreFocus
    prev := WinActive("A")
    if !FocusClaude()
        return
    Send("{Enter}")
    Sleep(80)
    if (RestoreFocus = "1" && prev)
        WinActivate("ahk_id " prev)
}

; Bring the Claude desktop window to the front. Returns 0 if not found.
FocusClaude() {
    global WinMatch
    if !WinExist(WinMatch) {
        TrayTip("Claude window not found",
                "Open the Claude desktop app, or set WinMatch in config.ini.", 3)
        return 0
    }
    WinActivate(WinMatch)
    return WinWaitActive(WinMatch, , 2)
}
